/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PrivateTrafficAggregatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "authorizeReporter"
      | "authorizedReporters"
      | "currentReportCycle"
      | "cycleAggregates"
      | "cycleInterval"
      | "emergencyPause"
      | "emergencyWithdraw"
      | "forceAdvanceCycle"
      | "getCurrentCycleInfo"
      | "getCycleAggregate"
      | "getRegionReporters"
      | "getRegionStats"
      | "getRegisteredRegions"
      | "getReportTimestamp"
      | "hasReported"
      | "isReporterAuthorized"
      | "lastCycleTime"
      | "manuallyFinalizeCycle"
      | "protocolId"
      | "regionData"
      | "registerRegion"
      | "registeredRegions"
      | "reports"
      | "revokeReporter"
      | "setCycleInterval"
      | "submitTrafficReport"
      | "transferAdmin"
      | "validRegions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CycleFinalized"
      | "RegionRegistered"
      | "ReportSubmitted"
      | "ReporterAuthorized"
      | "ReporterRevoked"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "authorizeReporter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedReporters",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentReportCycle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cycleAggregates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cycleInterval",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyPause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "forceAdvanceCycle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentCycleInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCycleAggregate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegionReporters",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegionStats",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegisteredRegions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReportTimestamp",
    values: [string, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasReported",
    values: [string, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isReporterAuthorized",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastCycleTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "manuallyFinalizeCycle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "regionData",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerRegion",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredRegions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reports",
    values: [BigNumberish, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeReporter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCycleInterval",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitTrafficReport",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validRegions",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizeReporter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedReporters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentReportCycle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cycleAggregates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cycleInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceAdvanceCycle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentCycleInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCycleAggregate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegionReporters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegionStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegisteredRegions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReportTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasReported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isReporterAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastCycleTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "manuallyFinalizeCycle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "regionData", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerRegion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredRegions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reports", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeReporter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCycleInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitTrafficReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validRegions",
    data: BytesLike
  ): Result;
}

export namespace CycleFinalizedEvent {
  export type InputTuple = [cycle: BigNumberish, totalReports: BigNumberish];
  export type OutputTuple = [cycle: bigint, totalReports: bigint];
  export interface OutputObject {
    cycle: bigint;
    totalReports: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegionRegisteredEvent {
  export type InputTuple = [region: string];
  export type OutputTuple = [region: string];
  export interface OutputObject {
    region: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReportSubmittedEvent {
  export type InputTuple = [
    reporter: AddressLike,
    region: string,
    cycle: BigNumberish
  ];
  export type OutputTuple = [reporter: string, region: string, cycle: bigint];
  export interface OutputObject {
    reporter: string;
    region: string;
    cycle: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReporterAuthorizedEvent {
  export type InputTuple = [reporter: AddressLike];
  export type OutputTuple = [reporter: string];
  export interface OutputObject {
    reporter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReporterRevokedEvent {
  export type InputTuple = [reporter: AddressLike];
  export type OutputTuple = [reporter: string];
  export interface OutputObject {
    reporter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivateTrafficAggregator extends BaseContract {
  connect(runner?: ContractRunner | null): PrivateTrafficAggregator;
  waitForDeployment(): Promise<this>;

  interface: PrivateTrafficAggregatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  authorizeReporter: TypedContractMethod<
    [reporter: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedReporters: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  currentReportCycle: TypedContractMethod<[], [bigint], "view">;

  cycleAggregates: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        totalReports: bigint;
        totalRegions: bigint;
        timestamp: bigint;
        isFinalized: boolean;
      }
    ],
    "view"
  >;

  cycleInterval: TypedContractMethod<[], [bigint], "view">;

  emergencyPause: TypedContractMethod<[], [void], "nonpayable">;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  forceAdvanceCycle: TypedContractMethod<[], [void], "nonpayable">;

  getCurrentCycleInfo: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        cycle: bigint;
        timeRemaining: bigint;
        totalRegions: bigint;
      }
    ],
    "view"
  >;

  getCycleAggregate: TypedContractMethod<
    [cycle: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        totalReports: bigint;
        totalRegions: bigint;
        timestamp: bigint;
        isFinalized: boolean;
      }
    ],
    "view"
  >;

  getRegionReporters: TypedContractMethod<
    [region: string, cycle: BigNumberish],
    [string[]],
    "view"
  >;

  getRegionStats: TypedContractMethod<
    [region: string, cycle: BigNumberish],
    [
      [bigint, bigint, boolean] & {
        totalReports: bigint;
        lastUpdate: bigint;
        hasData: boolean;
      }
    ],
    "view"
  >;

  getRegisteredRegions: TypedContractMethod<[], [string[]], "view">;

  getReportTimestamp: TypedContractMethod<
    [region: string, reporter: AddressLike, cycle: BigNumberish],
    [bigint],
    "view"
  >;

  hasReported: TypedContractMethod<
    [region: string, reporter: AddressLike, cycle: BigNumberish],
    [boolean],
    "view"
  >;

  isReporterAuthorized: TypedContractMethod<
    [reporter: AddressLike],
    [boolean],
    "view"
  >;

  lastCycleTime: TypedContractMethod<[], [bigint], "view">;

  manuallyFinalizeCycle: TypedContractMethod<[], [void], "nonpayable">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  regionData: TypedContractMethod<
    [arg0: BigNumberish, arg1: string],
    [
      [bigint, string, string, string, bigint, boolean] & {
        totalReports: bigint;
        aggregatedCongestion: string;
        aggregatedVehicles: string;
        aggregatedSpeed: string;
        lastUpdate: bigint;
        hasData: boolean;
      }
    ],
    "view"
  >;

  registerRegion: TypedContractMethod<
    [regionName: string],
    [void],
    "nonpayable"
  >;

  registeredRegions: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  reports: TypedContractMethod<
    [arg0: BigNumberish, arg1: string, arg2: AddressLike],
    [
      [string, string, string, bigint, string, boolean] & {
        congestionLevel: string;
        vehicleCount: string;
        averageSpeed: string;
        timestamp: bigint;
        reporter: string;
        isValid: boolean;
      }
    ],
    "view"
  >;

  revokeReporter: TypedContractMethod<
    [reporter: AddressLike],
    [void],
    "nonpayable"
  >;

  setCycleInterval: TypedContractMethod<
    [newInterval: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitTrafficReport: TypedContractMethod<
    [
      region: string,
      congestionLevel: BigNumberish,
      vehicleCount: BigNumberish,
      averageSpeed: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  transferAdmin: TypedContractMethod<
    [newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  validRegions: TypedContractMethod<[arg0: string], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "authorizeReporter"
  ): TypedContractMethod<[reporter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedReporters"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "currentReportCycle"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cycleAggregates"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        totalReports: bigint;
        totalRegions: bigint;
        timestamp: bigint;
        isFinalized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cycleInterval"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyPause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "forceAdvanceCycle"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCurrentCycleInfo"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        cycle: bigint;
        timeRemaining: bigint;
        totalRegions: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCycleAggregate"
  ): TypedContractMethod<
    [cycle: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        totalReports: bigint;
        totalRegions: bigint;
        timestamp: bigint;
        isFinalized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRegionReporters"
  ): TypedContractMethod<
    [region: string, cycle: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRegionStats"
  ): TypedContractMethod<
    [region: string, cycle: BigNumberish],
    [
      [bigint, bigint, boolean] & {
        totalReports: bigint;
        lastUpdate: bigint;
        hasData: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRegisteredRegions"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getReportTimestamp"
  ): TypedContractMethod<
    [region: string, reporter: AddressLike, cycle: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasReported"
  ): TypedContractMethod<
    [region: string, reporter: AddressLike, cycle: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isReporterAuthorized"
  ): TypedContractMethod<[reporter: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastCycleTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "manuallyFinalizeCycle"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "regionData"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: string],
    [
      [bigint, string, string, string, bigint, boolean] & {
        totalReports: bigint;
        aggregatedCongestion: string;
        aggregatedVehicles: string;
        aggregatedSpeed: string;
        lastUpdate: bigint;
        hasData: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerRegion"
  ): TypedContractMethod<[regionName: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registeredRegions"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "reports"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: string, arg2: AddressLike],
    [
      [string, string, string, bigint, string, boolean] & {
        congestionLevel: string;
        vehicleCount: string;
        averageSpeed: string;
        timestamp: bigint;
        reporter: string;
        isValid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeReporter"
  ): TypedContractMethod<[reporter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCycleInterval"
  ): TypedContractMethod<[newInterval: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitTrafficReport"
  ): TypedContractMethod<
    [
      region: string,
      congestionLevel: BigNumberish,
      vehicleCount: BigNumberish,
      averageSpeed: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "validRegions"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;

  getEvent(
    key: "CycleFinalized"
  ): TypedContractEvent<
    CycleFinalizedEvent.InputTuple,
    CycleFinalizedEvent.OutputTuple,
    CycleFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "RegionRegistered"
  ): TypedContractEvent<
    RegionRegisteredEvent.InputTuple,
    RegionRegisteredEvent.OutputTuple,
    RegionRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ReportSubmitted"
  ): TypedContractEvent<
    ReportSubmittedEvent.InputTuple,
    ReportSubmittedEvent.OutputTuple,
    ReportSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ReporterAuthorized"
  ): TypedContractEvent<
    ReporterAuthorizedEvent.InputTuple,
    ReporterAuthorizedEvent.OutputTuple,
    ReporterAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "ReporterRevoked"
  ): TypedContractEvent<
    ReporterRevokedEvent.InputTuple,
    ReporterRevokedEvent.OutputTuple,
    ReporterRevokedEvent.OutputObject
  >;

  filters: {
    "CycleFinalized(uint256,uint256)": TypedContractEvent<
      CycleFinalizedEvent.InputTuple,
      CycleFinalizedEvent.OutputTuple,
      CycleFinalizedEvent.OutputObject
    >;
    CycleFinalized: TypedContractEvent<
      CycleFinalizedEvent.InputTuple,
      CycleFinalizedEvent.OutputTuple,
      CycleFinalizedEvent.OutputObject
    >;

    "RegionRegistered(string)": TypedContractEvent<
      RegionRegisteredEvent.InputTuple,
      RegionRegisteredEvent.OutputTuple,
      RegionRegisteredEvent.OutputObject
    >;
    RegionRegistered: TypedContractEvent<
      RegionRegisteredEvent.InputTuple,
      RegionRegisteredEvent.OutputTuple,
      RegionRegisteredEvent.OutputObject
    >;

    "ReportSubmitted(address,string,uint256)": TypedContractEvent<
      ReportSubmittedEvent.InputTuple,
      ReportSubmittedEvent.OutputTuple,
      ReportSubmittedEvent.OutputObject
    >;
    ReportSubmitted: TypedContractEvent<
      ReportSubmittedEvent.InputTuple,
      ReportSubmittedEvent.OutputTuple,
      ReportSubmittedEvent.OutputObject
    >;

    "ReporterAuthorized(address)": TypedContractEvent<
      ReporterAuthorizedEvent.InputTuple,
      ReporterAuthorizedEvent.OutputTuple,
      ReporterAuthorizedEvent.OutputObject
    >;
    ReporterAuthorized: TypedContractEvent<
      ReporterAuthorizedEvent.InputTuple,
      ReporterAuthorizedEvent.OutputTuple,
      ReporterAuthorizedEvent.OutputObject
    >;

    "ReporterRevoked(address)": TypedContractEvent<
      ReporterRevokedEvent.InputTuple,
      ReporterRevokedEvent.OutputTuple,
      ReporterRevokedEvent.OutputObject
    >;
    ReporterRevoked: TypedContractEvent<
      ReporterRevokedEvent.InputTuple,
      ReporterRevokedEvent.OutputTuple,
      ReporterRevokedEvent.OutputObject
    >;
  };
}
